### PR TITLE
Ability to set relative ruleset path

### PR DESCRIPTION
**Pull request by nchursin**
Hi @ChuckJonas 

Seems, you no longer maintain the ext, still, I'll leave it here just in case 🙂
Just an ability to use relative paths for ruleset, so one can commit their rulesets to a repo

### CODE REVIEW

**Comment by ChuckJonas** [comment]
@nchursin ya, I don't use it anymore and don't have very much free time to work through updates.  Do you have any interest in taking it over?

**Comment by nchursin** [comment]
Sure, I have some spare time to maintain this

**Comment by ChuckJonas** [comment]
@nchursin awesome

I just merged all the open PR's.  Would you mind building and testing master? I seem to be locked out of my publishing account, but hopefully once I get in, we can figure out how to transfer the extension over to you.  

Or I don't mind being responsible for publishing, but I just don't have the time to build & test.

**Comment by nchursin** [comment]
Yup, no problem, I'll start testing right now

**Comment by ChuckJonas** [comment]
Thanks. I've re-authenticated, so let me know once you've finished and I'll publish.

**Comment by nchursin** [comment]
Everything looks fine.
My MS account is chursinn91@gmail.com you can add me as a publisher if you like

**Pull request merged**
