### PR TITLE
version bump 6.22

### PR DESCRIPTION
**Pull request by thombehrens**
pmd 6.22 adds support for Cognitive Complexity and for suppressing feedback with a // NOPMD comment. 

See release here: https://github.com/pmd/pmd/releases/tag/pmd_releases/6.22.0

### CODE REVIEW

**Comment by ChuckJonas** [comment]
Is there a new rule for this?  Would be good to add it to the default ruleset as well

**Comment by thombehrens** [comment]
Added rule according to [this](https://pmd.github.io/pmd-6.22.0/pmd_rules_apex_design.html#cognitivecomplexity) documentation; debugged the extension with the default ruleset and the examples given and everything looks o.k.

// NOPMD working as well.

**Comment by thombehrens** [comment]
... Do we want to remove Cyclomatic Complexity from the defaults? I know I will be instructing friends to update theirs. Looking at it, it may be in there twice right now? Line 43 and Line 61.

**Comment by ChuckJonas** [comment]
yea I haven't had a chance to look much into it, but I assume CognitiveComplexity is basically is considered an improved metric vs "Cyclomatic Complexity"?

If so, then ya.

**Comment by thombehrens** [comment]
It's certainly a matter of preference, but I know R. Soesmann originally wanted to deprecate the Cyclomatic Complexity rule entirely when Cognitive Complexity was released. On the [issue thread](https://github.com/pmd/pmd/issues/2162) they decided not to deprecate, but I still think many believe Cognitive Complexity should act as a replacement by default.

**Comment by ChuckJonas** [comment]
Awesome... I'll be publishing this (and a few other small changes over the weekend).

Thanks

**Pull request merged**
