### PR TITLE
4.0 release

### PR DESCRIPTION
**Pull request by ChuckJonas**
- upgraded csv pkg
- ignore .sfdx files #36
- improved recovery of bad csv data #38 (workaround fix)

### CODE REVIEW

**Comment by nchursin** [comment]
I sent another PR here, so we can have all the changes for 3.2 in one place

**Comment by ChuckJonas** [comment]
Hoping to release tomorrow!

@nchursin if you have some spare time before then, it would be much appreciated if you could test the build (I'll do the same).

**Comment by nchursin** [comment]
Yup, I'll also give it out to some guys in the office who use the plugin, so they can check it in action.

**Comment by nchursin** [comment]
I'll do #42 today too, so we can release that as well

**Comment by nchursin** [comment]
BTW since we're adding a new feature (PMD cache) according to SemVer we should increase major number, like `0.4.0`

**Comment by ChuckJonas** [comment]
@nchursin nice work...  I just ran through some smoke tests with #42 work.  Everything seems to be working.  🚢'n!

**Pull request merged**
