### PR TITLE
Bundle pmd

### PR DESCRIPTION
**Pull request by ChuckJonas**
@nchursin 

This update includes the binaries by default, updates the standard ruleset & fixes some bugs.  This should allow people to use the extension out of the box (#17 #12, etc)

Do you by chance have access to a windows machine?  I will be running tests on OSX but it would be good to fire it up on windows before publishing.

FYI: @ntotten has reached out about bundling this extension with the official salesforce pack.

### CODE REVIEW

**Comment by ChuckJonas** [comment]
I added the vscx package so you don't have to compile it yourself https://github.com/ChuckJonas/vscode-apex-pmd/releases/tag/0.2.0

**Comment by nchursin** [comment]
@ChuckJonas I'll be able to test it on Win tomorrow morning, Moscow time. Let's wait with the release until then.

**Comment by ChuckJonas** [comment]
closed in favor of broader 2.0 branch

**Comment by ChuckJonas** [comment]
@nchursin made a bunch more updates.  I created 2.0 branch and am going to update the pre-release `.vsix` to also incorporate your changes for #15

**Pull request closed without merging**
