### PR TITLE
0.5.10 - upgrade to PMD 6.55.0

### PR DESCRIPTION
**Pull request by pventurino**
Updates all libraries to the versions in 6.55.

Notable features from 6.42 to 6.55
- Support for user mode and system mode in CRUD methods
- Support for the new Assert class.
-

### CODE REVIEW

**Comment by pventurino** [comment]
Basically the same changes as #120. If you prefer to merge that one instead (which is already reviewed) works for me: I'm only trying to get support for the new Assert class

**Comment by adangel** [comment]
@pventurino : do you know, you can download PMD 6.55.0 separately and configure the path to it in the extension?

image

**Comment by pventurino** [comment]
@adangel  I didn't know that, I ended up packaging the newer version and installing it locally.
Now that I know, I might go back to the proper version, but I'll let my coworkers know about this. Thanks! :+1:

**Comment by ChuckJonas** [comment]
closing as we've released a version for PMD7

**Pull request closed without merging**
