### PR TITLE
Support XML metadata analysis

### LINKED ISSUE #96: Detect violations to Custom XML rules
The latest versions of PMD now support Custom Rules for XML metadata. Which is a super helpful feature for Salesforce Developers using PMD and PMD related IDE extensions as Salesforce store most of the "code" as XML files.

I am kindly asking to extend this extension to support that. Here is proof that it doesn't work with the current version.

### WORKS
My repo contains a **Custom XPath rule for Apex** that detects illegal use of `System.debug`:
https://github.com/rsoesemann/unhappy-soup/blob/master/ruleset.xml#L26

ApexPMD perfectly detects such an issue in 
https://github.com/rsoesemann/unhappy-soup/blob/master/force-app/main/default/classes/Voldemort.cls#L25

### DOESNT WORK
My repo also contains a **Custom XPath rule for XML** that detect unsafe Security Settings:
https://github.com/rsoesemann/unhappy-soup/blob/master/ruleset.xml#L57

Apex PMD does NOT find the problematic line in 
https://github.com/rsoesemann/unhappy-soup/blob/master/force-app/main/default/settings/Security.settings-meta.xml#L12

### PR DESCRIPTION
**Pull request by nawforce**
Fixes #96 

I was wondering about if this should be restricted to just XML files of known metadata formats, e.g. *.field-meta.xml etc etc. On balance I thought that might be more confusing than helpful and anyone using is a SF developer so most XML files probably do contain metadata.

### CODE REVIEW

**Comment by rsoesemann** [comment]
@nawforce thank you so much for contributing this important addition. I think *.xml is good enough. Even when *.*-meta.xml would restrict it more to Salesforce XML metadata. But as you have further specifying node names in the rule XPath which all are very SF specific I think thats fine.

**Comment by rsoesemann** [comment]
Good points @ChuckJonas.

- @nawforce please refer to my initial issue. it contains a public repo with a ruleset and issues for local testing
- Regarding the other changes. I think we should start a v1 as is (just the extension changed to `-meta.xml`) and do the other stuff later, when needed.

**Comment by nawforce** [comment]
@ChuckJonas `On Workspace` worked fine but when I updated the context menus I ran into an issue where VSCode is passing a Uri rather than a filename to PMD. To handle this I have introduced a new `Command` that is for use from the two menu contribution points. Without this the extension was passing a file://.. URI to PMD which was not happy to receive that. 

This also allows the menu text to be customised, the menus don't show the "category" text of the commands so I used `Static Analysis On File` as previously the `On File` was a little confusing without the category to give context.

**Comment by rsoesemann** [comment]
@nawforce @ChuckJonas Do you have any objections with merging and releasing this mvp?

**Comment by ChuckJonas** [comment]
I'll try to pull this down, test and release this afternoon.

**Comment by ChuckJonas** [comment]
Published in v0.5.9.

Please test and lmk if there are any issues. 

Thanks for the contributions.

**Pull request merged**
